---
- hosts: all
  vars:
    files_repo: ../files
  tasks:
    - name: COPY copy files
      copy:
        src: "{{ files_repo }}/{{ item.file }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      loop:
         - { file: 'smb.conf', dest: '/etc/samba/smb.conf', mode: '0644', owner: 'root', group: 'root' }
         - { file: 'bashrc_global', dest: '/data/config/bashrc_global', mode: '0644', owner: 'root', group: 'root' }

    - name: COPY sync var/www
      synchronize:
        src: "{{ files_repo }}/www"
        dest: "/var/www/"
