---
- hosts: all
  vars:
    files_repo: ../files
  tasks:
    - include_vars: ../vars/global.yml
    - name: COPY copy files
      copy:
        src: "{{ files_repo }}/conf/{{ item.file }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      loop:
         - { file: 'smb.conf', dest: '/etc/samba/smb.conf', mode: '0644', owner: 'root', group: 'root' }
         - { file: 'bashrc_global', dest: '/data/config/bashrc_global', mode: '0644', owner: 'root', group: 'root' }
         - { file: 'apache2.conf', dest: '/etc/apache2/apache2.conf', mode: '0644', owner: 'root', group: 'root' }

    - name: COPY sync var/www/html
      synchronize:
        src: "{{ files_repo }}/html"
        dest: "/var/www/"

    - name: COPY set owner+group for var/www/html
      file:
        dest: "/var/www"
        owner: "www-data"
        group: "www-data"
        recurse: yes

    - name: COPY replace variables in files
      replace:
        dest: /var/www/html/index.html
        regexp: '@IP@'
        replace: '{{ piserver_ip }}'
