---
- hosts: all
  tasks:
    - name: DISK create partition
      parted:
        device: /dev/sda
        number: 1
        flags: [ lvm ]
        state: present

    - name: DISK create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/sda1

    - name: DISK mount disk
      mount:
        fstype: ext4
        src: /dev/sda1
        path: /data
        state: mounted
