---
- hosts: all
  tasks:
    - name: EDIT stop service transmission
      service:
        name: transmission-daemon
        state: stopped

    - name: EDIT edit files
      lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { path: '/root/.bashrc', regexp: '^source /', line: 'source /data/config/bashrc_global' }
        - { path: '/home/pi/.bashrc', regexp: '^source /', line: 'source /data/config/bashrc_global' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "download-dir":', line: '    "download-dir": "/data/transmission/complete",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "incomplete-dir":', line: '    "incomplete-dir": "/data/transmission/inprogress",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "incomplete-dir-enabled":', line: '    "incomplete-dir-enabled": true,' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "rpc-whitelist":', line: '    "rpc-whitelist": "192.168.0.*",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "speed-limit-up":', line: '    "speed-limit-up": "25",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "speed-limit-up-enabled":', line: '    "speed-limit-up-enabled": true,' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "rpc-username":', line: '    "rpc-username": "pi",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "rpc-password":', line: '    "rpc-password": "pipass",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "umask":', line: '    "umask": "2",' }
        - { path: '/root/.vnc/config.d/vncserver-x11', regexp: '^AdminPassword=', line: 'AdminPassword=20002602ce080a9a238f6ae20ac6bb98' }
        - { path: '/root/.vnc/config.d/vncserver-x11', regexp: '^Password=', line: 'Password=20002602ce080a9a238f6ae20ac6bb98' }
        - { path: '/root/.vnc/config.d/vncserver-x11', regexp: '^Authentication=', line: 'Authentication=VncAuth' }
        - { path: '/root/.vnc/config.d/vncserver-x11', regexp: '^ConnNotifyTimeout=', line: 'ConnNotifyTimeout=0' }
