---
- hosts: all
  tasks:
    - include_vars: ../vars/global.yml
    - name: EDIT stop service transmission
      service:
        name: transmission-daemon
        state: stopped

    - name: EDIT edit files
      lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { path: '/root/.bashrc', regexp: '^source /', line: 'source /data/config/bashrc_global' }
        - { path: '/home/pi/.bashrc', regexp: '^source /', line: 'source /data/config/bashrc_global' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "download-dir":', line: '    "download-dir": "/data/transmission/complete",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "incomplete-dir":', line: '    "incomplete-dir": "/data/transmission/inprogress",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "incomplete-dir-enabled":', line: '    "incomplete-dir-enabled": true,' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "rpc-whitelist":', line: '    "rpc-whitelist": "{{ piserver_subnet_3 }}.*",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "speed-limit-up":', line: '    "speed-limit-up": "0",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "speed-limit-up-enabled":', line: '    "speed-limit-up-enabled": true,' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "rpc-username":', line: '    "rpc-username": "{{ piserver_username }}",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "rpc-password":', line: '    "rpc-password": "{{ piserver_password }}",' }
        - { path: '/etc/transmission-daemon/settings.json', regexp: '^    "umask":', line: '    "umask": "2",' }
        - { path: '/etc/dhcpcd.conf', regexp: '^interface', line: 'interface {{ piserver_interface }}' }
        - { path: '/etc/dhcpcd.conf', regexp: '^static\ ip_address', line: 'static ip_address={{ piserver_ip }}/{{ piserver_netmask }}' }
        - { path: '/etc/dhcpcd.conf', regexp: '^static\ routers', line: 'static routers={{ piserver_gateway }}' }
        - { path: '/etc/dhcpcd.conf', regexp: '^static\ domain\_name\_servers', line: 'static domain_name_servers={{ piserver_gateway }} 8.8.8.8' }
          
    - name: EDIT replace @IP@ with ip
      lineinfile:
        path: /var/www/html/index.html
        regexp: '@IP@'
        line: "{{ piserver_ip }}"
