---
- hosts: all
  tasks:
    - include_vars: ../vars/global.yml
    - name: NETWORK configuring interface file dhcpcd.conf
      copy:
        src: "../files/conf/dhcpcd.conf"
        dest: "/etc/dhcpcd.conf"
        mode: "664"
        owner: "root"
        group: "netdev"

    - name: NETWORK replace variables in dhcpcd.conf
      lineinfile:
        path: /etc/dhcpcd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: "^interface/", line: "interface {{ piserver_interface }}" }
        - { regexp: '^static\ ip_address=/', line: "static\ ip_address={{ piserver_ip }}/{{ piserver_netmask }}" }
        - { regexp: '^static\ routers=/', line: "static\ routers={{ piserver_gateway }}" }
        - { regexp: '^static\ domain_name_servers=/', line: "static\ domain_name_servers={{ piserver_gateway }}\ 8.8.8.8" }

