---
- hosts: all
  tasks:
    - include_vars: ../vars/global.yml
    - name: NETWORK configuring interface
      nmcli:
        conn_name: "System {{item.conn}}"
        ifname: "{{ item.conn }}"
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "{{ item.ipv4 }}"
        gw4: "{{ item.gw4 }}"
      loop:
        - { conn: '{{ piserver_interface }}', ipv4: '{{ piserver_ip }}', gw4: '{{ piserver_gateway }}' }
