---
- hosts: all
  tasks:
    - name: NETWORK configuring eth
      nmcli:
        conn_name: "System {{item.conn}}"
        ifname: {{item.conn}}
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "{{ item.ipv4 }}"
        gw4: "{{ item.gw4 }}"
      loop:
        - { conn: 'wlan0', ipv4: '192.168.0.222', gw4: '192.168.0.1' }
