---
- hosts: all
  tasks:
    - name: PACKAGES install
      apt:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      loop:
        - { name: 'transmission', state: 'latest'}
        - { name: 'transmission-daemon', state: 'latest'}
        - { name: 'samba', state: 'latest'}
        - { name: 'samba-common-bin', state: 'latest'}
        - { name: 'apache2', state: 'latest'}
        - { name: 'vim', state: 'latest'}
        - { name: 'wget', state: 'latest'}
        - { name: 'mariadb-server', state: 'latest'}

    - name: PACKAGES autoremove
      apt:
        autoremove: yes

    - name: PACKAGES clean
      apt:
        autoclean: yes
