---
- hosts: all
  tasks:
    - name: [PACKAGES] install
      apt:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      loop:
        - { name: 'transmission', state: 'latest'}
        - { name: 'transmission-daemon', state: 'latest'}
        - { name: 'samba', state: 'latest'}
        - { name: 'samba-common-bin', state: 'latest'}
        #- { name: 'samba-client', state: 'latest'}
        #- { name: 'cifs-utils', state: 'latest'}
        - { name: 'chromium-browser', state: 'latest'}


    - name: [PACKAGES] autoremove
      apt:
        autoremove: yes

    - name: [PACKAGES] clean
      apt:
        autoclean: yes
