---
- hosts: all
  tasks:
    - name: SERVICES enable and start services
      service:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
        enabled: '{{ item.enabled }}'
      loop:
        - { name: 'smbd', state: 'started', enabled: 'yes'}
        - { name: 'transmission-daemon', state: 'started', enabled: 'yes'}
        - { name: 'apache2', state: 'started', enabled: 'yes'}


    - name: SERVICES create user for service SMB
      shell: "(echo {{ item.smbpasswd }}; echo {{ item.smbpasswd }}) | smbpasswd -s -a {{ item.name }}"
      loop:
        - { name: 'piserver', smbpasswd: 'pipass'}
