---
- hosts: all
  tasks:
    - name: [SERVICES] manage services
      service:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
        enabled: '{{ item.enabled }}'
      loop:
        - { name: 'samba_daemon', state: 'started', enabled: 'yes'}
        - { name: 'transmission-daemon', state: 'started', enabled: 'yes'}
