---
- hosts: all
  tasks:
    - include_vars: ../vars/global.yml
    - name: SERVICES enable and start services
      service:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
        enabled: '{{ item.enabled }}'
      loop:
        - { name: 'smbd', state: 'started', enabled: 'yes'}
        - { name: 'transmission-daemon', state: 'started', enabled: 'yes'}
        - { name: 'apache2', state: 'started', enabled: 'yes'}


    - name: SERVICES create user for service SMB
      shell: "(echo {{ piserver_password }}; echo {{ piserver_password }}) | smbpasswd -s -a {{ piserver_username }}"
#      loop:
#        - { name: 'piserver', smbpasswd: 'pipass'}
