---
- hosts: all
  tasks:
    - include_vars: ../vars/global.yml
    - name: STRUCTURE create dirs
      file:
        path:  '{{ item.path }}'
        state: directory
        mode: '{{ item.mode }}'
        owner: '{{ item.owner }}'
        group: '{{ item.group }}'
      loop:
        - { path: '/data', mode: '0777', owner: 'root', group: 'root'}
        - { path: '/data/config', mode: '0777', owner: 'root', group: 'root'}
        - { path: '/data/upload', mode: '0770', owner: '{{ piserver_username }}', group: '{{ piserver_username }}'}
        - { path: '/data/transmission', mode: '0770', owner: 'debian-transmission', group: 'debian-transmission'}
        - { path: '/data/transmission/inprogress', mode: '0770', owner: 'debian-transmission', group: 'debian-transmission'}
        - { path: '/data/transmission/complete', mode: '0770', owner: 'debian-transmission', group: 'debian-transmission'}
        - { path: '/var/www/html/media', mode: '0770', owner: 'www-data', group: 'www-data'}
